### ISSUE TITLE
need error handling when no internet connection or timeout

### ISSUE THREAD

**Issue by anggit97** [MoIbrahim15/Android-Kotlin-MVI-CleanArchitecture#1]
I think this project need to handling when there is no internect connection or timeout. it can be handle below class

https://github.com/MoIbrahim15/Android-Kotlin-MVI-CleanArchitecture/blob/master/app/src/main/java/com/mi/mvi/utils/response_handler/ErrorHandler.kt

**Comment by MoIbrahim15** [comment]
Hello Anggit,
Checkout latest branch revamp/flows_channels everything is handled

**Comment by MoIbrahim15** [comment]
`

**Comment by MoIbrahim15** [comment]
Hello Anggit,
Checkout latest branch revamp/flows_channels everything is handled

**Comment by anggit97** [comment]
oke, great!
