### ISSUE TITLE
Build error 

### ISSUE THREAD

**Issue by Abed-Murad** [MoIbrahim15/Android-Kotlin-MVI-CleanArchitecture#2]
`C:\Android-Kotlin-MVI-CleanArchitecture\build\build-attribution\androidGradlePluginAttributionData: The process cannot access the file because it is being used by another process.`

I get this error when I try to run the app on the master branch.

**Comment by MoIbrahim15** [comment]
Hello @Abed-Murad,
Do This
File -> Invalidate Caches / Restart.. -> Invalidate and Restart
